apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: sebasnadu/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              # Set directly the value
              # value: "story"
              # Or use a configmap file
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          # Creates a temporary directory on the node
          # emptyDir: {}
          # hostPath can be used instead of emptyDir. It creates a directory on the host machine
          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: host-pvc
